name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  call-workflow-passing-data:
    uses: Jobsby/test_wf_called/.github/workflows/reusable_workflow_remote.yml@main
    with:
      cumulus_gcp_json_key_identifier: MY_SECRET1
      input_name: Run workflow reusable remote with input
    secrets: inherit
