name: Call Reusable Workflow
run-name: Call Reusable Workflow from ${{ github.actor }}
on: workflow_dispatch
permissions: read-all
jobs:
  call-workflow-passing-data:
    uses: Jobsby/test_wf_called/.github/workflows/reusable_workflow_remote.yml@main
    with:
      cumulus_gcp_json_key_identifier: MY_CALLER_SECRET
      input_name: Run workflow reusable remote with input
    secrets: inherit
